<!doctype html>
<html lang="ro" xmlns:th="http://www.w3.org/1999/xhtml">

<head>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4253419731329045"
        crossorigin="anonymous"></script>

    <link rel="canonical" th:href="${canonicalUrl}" />
    <link rel="icon" type="image/png" href="/nume-aplicatie/images/favicon.png">
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-7Q2536ZKL2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        window.gtag = function () { dataLayer.push(arguments); };
        gtag('consent', 'default', {
            'wait_for_update': 500,
            'region': ['RO'],
            'ad_storage': 'denied',
            'analytics_storage': 'denied',
            'ad_user_data': 'denied',
            'ad_personalization': 'denied'
        });
        gtag('js', new Date());
        gtag('config', 'G-7Q2536ZKL2');
    </script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title th:text="${lesson.title}">Lesson</title>
    <link rel="stylesheet" th:href="@{/css/styles.css}">
    <style>
        body {
            background: #ffffff;
        }
    </style>
</head>

<body th:with="activeTopic='C-sharp', activeChapter='10.Colectii', activeLesson='1.Lista List_T_'">
    <button class="mobile-sidebar-toggle" onclick="toggleMobileSidebar()">☰</button>
    <div th:replace="~{fragments/nav :: nav}"></div>
    <div class="top-nav">
        <th:block th:each="topic : ${topics}">
            <a th:href="@{'/lectii/topic/' + ${topic.id}}" th:text="${topic.name}"
                th:classappend="${topic.id} == ${activeTopicId} ? 'active' : ''"> </a>
        </th:block>
    </div>
    <div class="layout">
        <div class="mobile-sidebar" id="mobileSidebar">
            <button class="close-btn" onclick="toggleSidebar()">✖</button>
            <ul class="chapter-list">
                <th:block th:each="chapter : ${chapters}">
                    <li class="chapter-item" th:classappend="${chapter.id} == ${activeChapterId} ? 'open' : ''">
                        <div class="chapter-title" onclick="toggleChapter(this)">
                            <strong th:text="${chapter.title}"></strong> <span class="arrow">▼</span>
                        </div>
                        <ul class="lesson-list">
                            <th:block th:each="lesson : ${chapter.lessons}">
                                <li><a th:href="@{'/lectii/' +
${#strings.toLowerCase(#strings.replace(chapter.topic.name, ' ', '-'))} + '/' +
${#strings.toLowerCase(#strings.replace(chapter.title, ' ', '-'))} + '/' +
${#strings.toLowerCase(#strings.replace(lesson.title, ' ', '-'))} }" th:text="${lesson.title}"
                                        th:classappend="${lesson.id} == ${activeLessonId} ? 'active' : ''"> </a></li>
                            </th:block>
                        </ul>
                    </li>
                </th:block>
            </ul>
        </div>
        <aside class="sidebar">
            <ul class="sidebar-list">
                <th:block th:each="chapter : ${chapters}">
                    <li class="chapter-item" th:classappend="${chapter.id} == ${activeChapterId} ? 'open' : ''">
                        <div class="chapter-toggle" onclick="toggleLessons(this)">
                            <span th:text="${chapter.title}">Chapter</span>
                        </div>
                        <ul class="lesson-list hidden">
                            <th:block th:each="lesson : ${chapter.lessons}">
                                <li><a th:href="@{'/lectii/' +
${#strings.toLowerCase(#strings.replace(chapter.topic.name, ' ', '-'))} + '/' +
${#strings.toLowerCase(#strings.replace(chapter.title, ' ', '-'))} + '/' +
${#strings.toLowerCase(#strings.replace(lesson.title, ' ', '-'))} }" th:text="${lesson.title}"
                                        th:classappend="${lesson.id} == ${activeLessonId} ? 'active' : ''"> </a></li>
                            </th:block>
                        </ul>
                    </li>
                </th:block>
            </ul>
        </aside>
        <main class="content">
            <div class="document-container">

<h1 class="main-title">Excepții</h1>
<h2 class="subtitle">Tratamentul excepțiilor</h2>
<p class="paragraph">În timpul rulării unui program pot apărea diverse erori. De exemplu, la transmiterea unui fișier prin rețea se poate întrerupe conexiunea sau pot fi introduse date incorecte și nepermise, care pot duce la prăbușirea programului. Astfel de erori se numesc excepții. O excepție reprezintă un obiect temporar de orice tip, care este folosit pentru a semnala o eroare. Scopul unui obiect-excepție este de a transmite informația din punctul în care a apărut eroarea către codul care ar trebui să o trateze. Dacă excepția nu este tratată, atunci programul se închide la apariția acesteia.</p>
<p class="paragraph">De exemplu, în următorul program are loc o împărțire de numere:</p>
<div class="code-inline"><pre><code>#include&nbsp;&lt;iostream&gt;<br>&nbsp;<br>double&nbsp;divide(int&nbsp;a,&nbsp;int&nbsp;b)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;a&nbsp;/&nbsp;b;<br>}<br>&nbsp;<br>int&nbsp;main()<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;x{500};<br>&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;y{};<br>&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;z&nbsp;{divide(x,&nbsp;y)};<br>&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;z&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;&quot;The&nbsp;End...&quot;&nbsp;&lt;&lt;&nbsp;std::endl;<br>}</code></pre></div>
<p class="paragraph">Acest program se va compila cu succes, dar în timpul execuției va apărea o eroare deoarece în cod se face împărțire la zero, iar programul se va închide brusc.</p>
<p class="paragraph">Pe de o parte, putem adăuga în funcția divide o verificare și efectua împărțirea doar dacă parametrul b este diferit de 0. Totuși, trebuie oricum să returnăm un rezultat din funcția divide – un anumit număr. Adică nu putem scrie pur și simplu:</p>
<div class="code-inline"><pre><code>double&nbsp;divide(int&nbsp;a,&nbsp;int&nbsp;b)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(b)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;a&nbsp;/&nbsp;b;<br>&nbsp;&nbsp;&nbsp;&nbsp;else<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;&quot;Error!&nbsp;b&nbsp;must&nbsp;not&nbsp;be&nbsp;equal&nbsp;to&nbsp;0&quot;&nbsp;&lt;&lt;&nbsp;std::endl;<br>}</code></pre></div>
<p class="paragraph">În acest caz trebuie să informăm sistemul despre eroare. Pentru asta se folosește operatorul throw.</p>
<p class="paragraph">Operatorul throw generează o excepție. Prin intermediul lui putem transmite informații despre eroare. De exemplu, funcția divide ar putea arăta astfel:</p>
<div class="code-inline"><pre><code>double&nbsp;divide(int&nbsp;a,&nbsp;int&nbsp;b)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(b)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;a&nbsp;/&nbsp;b;<br>&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;&quot;Division&nbsp;by&nbsp;zero!&quot;;<br>}<br></code></pre></div>
<p class="paragraph">Adică, dacă b este 0, se generează o excepție.</p>
<p class="paragraph">Dar această excepție trebuie tratată în codul care apelează funcția divide. Pentru tratarea excepțiilor se folosește construcția try...catch. Are forma următoare:</p>
<div class="code-inline"><pre><code>try<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;instrucțiuni&nbsp;care&nbsp;pot&nbsp;genera&nbsp;o&nbsp;excepție<br>}<br>catch(declarație_excepție)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;tratarea&nbsp;excepției<br>}</code></pre></div>
<p class="paragraph">În blocul de după cuvântul-cheie try se află codul care poate genera o excepție.</p>
<p class="paragraph">După catch, între paranteze, este un parametru care primește informația despre excepție. Urmează apoi blocul unde are loc tratarea.</p>
<p class="paragraph">Să modificăm întreg codul astfel:</p>
<div class="code-inline"><pre><code>#include&nbsp;&lt;iostream&gt;<br>&nbsp;<br>double&nbsp;divide(int&nbsp;a,&nbsp;int&nbsp;b)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(b)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;a&nbsp;/&nbsp;b;<br>&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;&quot;Division&nbsp;by&nbsp;zero!&quot;;<br>}<br>&nbsp;<br>int&nbsp;main()<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;x{500};<br>&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;y{};<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;try<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;z&nbsp;{divide(x,&nbsp;y)};<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;z&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(...)<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;&quot;Error!&quot;&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;&quot;The&nbsp;End...&quot;&nbsp;&lt;&lt;&nbsp;std::endl;<br>}</code></pre></div>
<p class="paragraph">Codul care poate genera o excepție — apelul funcției divide — este plasat în blocul try.</p>
<p class="paragraph">În blocul catch are loc tratarea. Punctele de suspensie din catch(...) permit tratarea oricărei excepții.</p>
<p class="paragraph">Astfel, când se execută linia:</p>
<div class="code-inline"><pre><code>double&nbsp;z&nbsp;{divide(x,&nbsp;y)};</code></pre></div>
<p class="paragraph">Se va genera o excepție, așa că instrucțiunile următoare din blocul try nu vor fi executate, iar controlul va fi transferat către catch, unde se afișează un mesaj de eroare. După blocul catch, programul nu se va închide brusc, ci își va continua execuția:</p>
<div class="code-inline"><pre><code>Error!<br>The&nbsp;End...</code></pre></div>
<p class="paragraph">Totuși, în acest caz știm doar că a apărut o eroare, dar nu și ce fel de eroare. Prin urmare, în parametru la catch putem primi mesajul transmis de throw:</p>
<div class="code-inline"><pre><code>#include&nbsp;&lt;iostream&gt;<br>&nbsp;<br>double&nbsp;divide(int&nbsp;a,&nbsp;int&nbsp;b)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(b)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;a&nbsp;/&nbsp;b;<br>&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;&quot;Division&nbsp;by&nbsp;zero!&quot;;<br>}<br>&nbsp;&nbsp;<br>int&nbsp;main()<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;x{500};<br>&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;y{};<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;try<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;z&nbsp;{divide(x,&nbsp;y)};<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;z&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(const&nbsp;char*&nbsp;error_message)<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;error_message&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;&quot;The&nbsp;End...&quot;&nbsp;&lt;&lt;&nbsp;std::endl;<br>}</code></pre></div>
<p class="paragraph">Cu ajutorul parametrului const char* error_message obținem mesajul transmis de throw și îl afișăm. De ce const char*? Pentru că după throw avem un literal de tip șir de caractere, adică exact const char*. Ieșirea în acest caz:</p>
<div class="code-inline"><pre><code>Division&nbsp;by&nbsp;zero!<br>The&nbsp;End...</code></pre></div>
<p class="paragraph">Astfel, putem afla natura exactă a excepției. În mod similar, putem transmite informații și prin alte tipuri, de exemplu, std::string:</p>
<div class="code-inline"><pre><code>throw&nbsp;std::string{&quot;Division&nbsp;by&nbsp;zero!!&quot;};</code></pre></div>
<p class="paragraph">Și atunci în blocul catch folosim:</p>
<div class="code-inline"><pre><code>catch&nbsp;(std::string&nbsp;error_message)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;error_message&nbsp;&lt;&lt;&nbsp;std::endl;<br>}</code></pre></div>
<p class="paragraph">Dacă excepția nu este tratată, se va apela funcția std::terminate() (din modulul &lt;exception&gt;), care, la rândul său, apelează funcția std::abort() (din &lt;cstdlib&gt;), ceea ce duce la închiderea programului.</p>
<p class="paragraph">Există foarte multe funcții în biblioteca standard C++ și în biblioteci externe. Se pune întrebarea: pe care să le plasăm într-un bloc try-catch pentru a evita închiderea neașteptată a programului? În primul rând, documentația funcției (dacă există) poate ajuta. Un alt semnal este cuvântul-cheie noexcept, care indică faptul că o funcție nu va genera excepții. De exemplu:</p>
<div class="code-inline"><pre><code>void&nbsp;print(int&nbsp;argument)&nbsp;noexcept;</code></pre></div>
<p class="paragraph">Aici indicăm că funcția print() nu va genera niciodată excepții. Așadar, dacă vedem o astfel de funcție, nu este necesar să o plasăm într-un bloc try-catch.</p>
<h2 class="subtitle">Crearea unui obiect de excepție</h2>
<p class="paragraph">În tratarea excepțiilor este important de reținut că atunci când un obiect este transmis operatorului throw, blocul catch primește o copie a acelui obiect. Iar această copie există doar în interiorul blocului catch.</p>
<p class="paragraph">Pentru tipuri primare, precum int, copierea valorii poate să nu afecteze performanța programului. Însă, când este vorba de obiecte de clasă, costurile pot fi mai mari. Prin urmare, în acest caz, obiectele sunt de obicei transmise prin referință, de exemplu:</p>
<div class="code-inline"><pre><code>#include&nbsp;&lt;iostream&gt;<br>&nbsp;<br>double&nbsp;divide(int&nbsp;a,&nbsp;int&nbsp;b)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(b)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;a&nbsp;/&nbsp;b;<br>&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::string{&quot;Division&nbsp;by&nbsp;zero!&quot;};<br>}<br>&nbsp;&nbsp;<br>int&nbsp;main()<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;x{500};<br>&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;y{};<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;try<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;z&nbsp;{divide(x,&nbsp;y)};<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;z&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(const&nbsp;std::string&amp;&nbsp;error_message)&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;șirul&nbsp;este&nbsp;transmis&nbsp;prin&nbsp;referință<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;error_message&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;&quot;The&nbsp;End...&quot;&nbsp;&lt;&lt;&nbsp;std::endl;<br>}</code></pre></div>
<h2 class="subtitle">Tratarea și generarea mai multor tipuri de excepții</h2>
<p class="paragraph">Putem genera și trata mai multe situații excepționale. Să presupunem că vrem ca, la împărțire, împărțitorul (al doilea număr) să nu fie mai mare decât deîmpărțitul (primul număr):</p>
<div class="code-inline"><pre><code>#include&nbsp;&lt;iostream&gt;<br>&nbsp;<br>double&nbsp;divide(int&nbsp;a,&nbsp;int&nbsp;b)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;if(!b)&nbsp;&nbsp;//&nbsp;dacă&nbsp;b&nbsp;==&nbsp;0<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;0;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;if(b&nbsp;&gt;&nbsp;a)&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;&quot;The&nbsp;second&nbsp;number&nbsp;is&nbsp;greater&nbsp;than&nbsp;the&nbsp;first&nbsp;one&quot;;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;a&nbsp;/&nbsp;b;<br>}<br>&nbsp;<br>void&nbsp;test(int&nbsp;a,&nbsp;int&nbsp;b)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;try<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;result&nbsp;{divide(a,&nbsp;b)};<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;result&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(int&nbsp;code)<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;&quot;Error&nbsp;code:&nbsp;&quot;&nbsp;&lt;&lt;&nbsp;code&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(const&nbsp;char*&nbsp;error_message)<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;error_message&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>}<br>&nbsp;&nbsp;<br>int&nbsp;main()<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;test(100,&nbsp;20);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;5<br>&nbsp;&nbsp;&nbsp;&nbsp;test(100,&nbsp;0);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Error&nbsp;code:&nbsp;0<br>&nbsp;&nbsp;&nbsp;&nbsp;test(100,&nbsp;1000);&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;The&nbsp;second&nbsp;number&nbsp;is&nbsp;greater&nbsp;than&nbsp;the&nbsp;first&nbsp;one<br>}</code></pre></div>
<p class="paragraph">În funcția divide, în funcție de valoarea lui b, operatorul throw primește fie un număr:</p>
<div class="code-inline"><pre><code>throw&nbsp;0;</code></pre></div>
<p class="paragraph">fie un literal de tip șir de caractere:</p>
<div class="code-inline"><pre><code>throw&nbsp;&quot;The&nbsp;second&nbsp;number&nbsp;is&nbsp;greater&nbsp;than&nbsp;the&nbsp;first&nbsp;one&quot;;</code></pre></div>
<p class="paragraph">Pentru a testa funcția divide s-a definit o altă funcție – test, unde apelul către divide() este plasat într-un bloc try...catch. Deoarece putem avea două tipuri de excepții — int și const char*, definim două blocuri catch pentru fiecare tip:</p>
<div class="code-inline"><pre><code>catch&nbsp;(int&nbsp;code)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;&quot;Error&nbsp;code:&nbsp;&quot;&nbsp;&lt;&lt;&nbsp;code&nbsp;&lt;&lt;&nbsp;std::endl;<br>}<br>catch&nbsp;(const&nbsp;char*&nbsp;error_message)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;error_message&nbsp;&lt;&lt;&nbsp;std::endl;<br>}</code></pre></div>
<p class="paragraph">În main, apelăm funcția test cu diverse valori. La:</p>
<div class="code-inline"><pre><code>test(100,&nbsp;20);</code></pre></div>
<p class="paragraph">nu apar excepții, iar rezultatul este afișat.</p>
<p class="paragraph">La:</p>
<div class="code-inline"><pre><code>test(100,&nbsp;0);</code></pre></div>
<p class="paragraph">se aruncă o excepție int, deci se va trata în:</p>
<div class="code-inline"><pre><code>catch&nbsp;(int&nbsp;code)</code></pre></div>
<p class="paragraph">La:</p>
<div class="code-inline"><pre><code>test(100,&nbsp;1000);</code></pre></div>
<p class="paragraph">b este mai mare ca a, deci se aruncă un const char* și se tratează în:</p>
<div class="code-inline"><pre><code>catch&nbsp;(const&nbsp;char*&nbsp;error_message)</code></pre></div>
<p class="paragraph">Ieșirea va fi:</p>
<div class="code-inline"><pre><code>5<br>Error&nbsp;code:&nbsp;0<br>The&nbsp;second&nbsp;number&nbsp;is&nbsp;greater&nbsp;than&nbsp;the&nbsp;first&nbsp;one</code></pre></div>
<p class="paragraph">Poate exista și situația în care o excepție este generată într-un bloc try-catch, dar nu există un bloc catch compatibil:</p>
<div class="code-inline"><pre><code>void&nbsp;test(int&nbsp;a,&nbsp;int&nbsp;b)<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;try<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;result&nbsp;{divide(a,&nbsp;b)};<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;result&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(const&nbsp;char*&nbsp;error_message)<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;error_message&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>}</code></pre></div>
<p class="paragraph">Aici, dacă se aruncă throw 0;, nu există un catch (int) corespunzător și programul se va închide brusc.</p>
<h2 class="subtitle">try-catch și destructori</h2>
<p class="paragraph">Este important de știut că dacă într-un bloc try se creează obiecte, atunci la apariția unei excepții li se vor apela destructorii. De exemplu:</p>
<div class="code-inline"><pre><code>#include&nbsp;&lt;iostream&gt;<br>&nbsp;<br>class&nbsp;Person<br>{<br>public:<br>&nbsp;&nbsp;&nbsp;&nbsp;Person(std::string&nbsp;name)&nbsp;:name{&nbsp;name&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;&quot;Person&nbsp;&quot;&nbsp;&lt;&lt;&nbsp;name&nbsp;&lt;&lt;&nbsp;&quot;&nbsp;created&quot;&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;~Person()<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cout&nbsp;&lt;&lt;&nbsp;&quot;Person&nbsp;&quot;&nbsp;&lt;&lt;&nbsp;name&nbsp;&lt;&lt;&nbsp;&quot;&nbsp;deleted&quot;&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;print()<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;&quot;Print&nbsp;Error&quot;;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>private:<br>&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;name;<br>};<br>&nbsp;<br>int&nbsp;main()<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;try<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Person&nbsp;tom{&nbsp;&quot;Tom&quot;&nbsp;};<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tom.print();&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;aici&nbsp;se&nbsp;aruncă&nbsp;excepția<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(const&nbsp;char*&nbsp;error)<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::cerr&nbsp;&lt;&lt;&nbsp;error&nbsp;&lt;&lt;&nbsp;std::endl;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>}</code></pre></div>
<p class="paragraph">Clasa Person are un destructor care afișează un mesaj. În funcția print se aruncă o excepție.</p>
<p class="paragraph">În main, în blocul try se creează un obiect Person, apoi se apelează print, care generează excepția. Înainte ca controlul să ajungă în catch, destructorul obiectului este apelat automat. Ieșirea va fi:</p>
<div class="code-inline"><pre><code>Person&nbsp;Tom&nbsp;created<br>Person&nbsp;Tom&nbsp;deleted<br>Print&nbsp;Error</code></pre></div>
<p class="paragraph">Acest comportament garantează eliberarea resurselor chiar și când apar excepții.</p>
            </div>
        </main>
        <aside class="ad-section">
            <div class="ad-box">
                <p>Google Ad Here</p>
            </div>
            <div class="ad-box">
                <p>Promo: SQL Beginner Guide</p>
            </div>
        </aside>
    </div>
    <div class="lesson-navigation">
        <th:block th:if="${previousLesson != null}">
            <a th:href="@{'/lectii/' +
            ${#strings.toLowerCase(#strings.replace(previousLesson.chapter.topic.name, ' ', '-'))} + '/' +
            ${#strings.toLowerCase(#strings.replace(previousLesson.chapter.title, ' ', '-'))} + '/' +
            ${#strings.toLowerCase(#strings.replace(previousLesson.title, ' ', '-'))} }" class="nav-button">← Lecția
                anterioară</a>
        </th:block>
        <th:block th:if="${nextLesson != null}">
            <a th:href="@{'/lectii/' +
            ${#strings.toLowerCase(#strings.replace(nextLesson.chapter.topic.name, ' ', '-'))} + '/' +
            ${#strings.toLowerCase(#strings.replace(nextLesson.chapter.title, ' ', '-'))} + '/' +
            ${#strings.toLowerCase(#strings.replace(nextLesson.title, ' ', '-'))} }" class="nav-button">Lecția
                următoare →</a>
        </th:block>
    </div>
    <div th:replace="~{fragments/footer :: footer}"></div>
    <script th:src="@{/js/script.js}" defer></script>
</body>
</html>
