<!doctype html>
<html lang="ro" xmlns:th="http://www.w3.org/1999/xhtml">
 <head>
    <link rel="icon" type="image/png" href="/nume-aplicatie/images/favicon.png">
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-7Q2536ZKL2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      window.gtag = function () { dataLayer.push(arguments); };
      gtag('consent', 'default', {
        'wait_for_update': 500,
        'region': ['RO'],
        'ad_storage': 'denied',
        'analytics_storage': 'denied',
        'ad_user_data': 'denied',
        'ad_personalization': 'denied'
      });
      gtag('js', new Date());
      gtag('config', 'G-7Q2536ZKL2');
    </script>


  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title th:text="${lesson.title}">Lesson</title>
  <link rel="stylesheet" th:href="@{/css/styles.css}">
  <style>body { background: #ffffff; }</style>
 </head>
 <body th:with="activeTopic='JavaScript', activeChapter='8.Tratarea erorilor', activeLesson='1.Tratarea erorilor'">
  <button class="mobile-sidebar-toggle" onclick="toggleMobileSidebar()">☰</button>
  <div th:replace="~{fragments/nav :: nav}"></div>
  <div class="top-nav">
   <th:block th:each="topic : ${topics}">
    <a th:href="@{'/lectii/topic/' + ${topic.id}}" th:text="${topic.name}" th:classappend="${topic.id} == ${activeTopicId} ? 'active' : ''"> </a>
   </th:block>
  </div>
  <div class="layout">
   <div class="mobile-sidebar" id="mobileSidebar">
    <button class="close-btn" onclick="toggleSidebar()">✖</button>
    <ul class="chapter-list">
     <th:block th:each="chapter : ${chapters}">
      <li class="chapter-item" th:classappend="${chapter.id} == ${activeChapterId} ? 'open' : ''">
       <div class="chapter-title" onclick="toggleChapter(this)">
        <strong th:text="${chapter.title}"></strong> <span class="arrow">▼</span>
       </div>
       <ul class="lesson-list">
        <th:block th:each="lesson : ${chapter.lessons}">
         <li><a th:href="@{'/lectii/' +
    ${#strings.toLowerCase(#strings.replace(chapter.topic.name, ' ', '-'))} + '/' +
    ${#strings.toLowerCase(#strings.replace(chapter.title, ' ', '-'))} + '/' +
    ${#strings.toLowerCase(#strings.replace(lesson.title, ' ', '-'))} }" th:text="${lesson.title}" th:classappend="${lesson.id} == ${activeLessonId} ? 'active' : ''"> </a></li>
        </th:block>
       </ul></li>
     </th:block>
    </ul>
   </div>
   <aside class="sidebar">
    <ul class="sidebar-list">
     <th:block th:each="chapter : ${chapters}">
      <li class="chapter-item" th:classappend="${chapter.id} == ${activeChapterId} ? 'open' : ''">
       <div class="chapter-toggle" onclick="toggleLessons(this)">
        <span th:text="${chapter.title}">Chapter</span>
       </div>
       <ul class="lesson-list hidden">
        <th:block th:each="lesson : ${chapter.lessons}">
         <li><a th:href="@{'/lectii/' +
    ${#strings.toLowerCase(#strings.replace(chapter.topic.name, ' ', '-'))} + '/' +
    ${#strings.toLowerCase(#strings.replace(chapter.title, ' ', '-'))} + '/' +
    ${#strings.toLowerCase(#strings.replace(lesson.title, ' ', '-'))} }" th:text="${lesson.title}" th:classappend="${lesson.id} == ${activeLessonId} ? 'active' : ''"> </a></li>
        </th:block>
       </ul></li>
     </th:block>
    </ul>
   </aside>
   <main class="content">
    <div class="document-container">
     <h1 class="main-title">Tratarea erorilor</h1>
     <h2 class="subtitle">Construcția try..catch..finally</h2>
     <p class="paragraph">În timpul execuției programului, pot apărea diferite erori care perturbă fluxul normal al programului și, uneori, determină întreruperea execuției acestuia. Limbajul JavaScript dispune de instrumente pentru gestionarea acestor situații.</p>
     <p class="paragraph">O situație simplă este apelarea unei funcții care nu există:</p>
     <div class="code-inline">
      <pre><code>callSomeFunc();<br><br>console.log("Restul&nbsp;instrucțiunilor");</code></pre>
     </div>
     <p class="paragraph">Aici se apelează funcția callSomeFunc(), care nu este definită nicăieri. Prin urmare, la apelul acestei funcții, ne confruntăm cu o eroare.</p>
     <div class="code-inline">
      <pre><code>Uncaught&nbsp;ReferenceError:&nbsp;callSomeFunc&nbsp;is&nbsp;not&nbsp;defined</code></pre>
     </div>
     <p class="paragraph">Toate celelalte instrucțiuni care urmează după linia unde apare eroarea nu sunt executate. Programul își încheie execuția.</p>
     <p class="paragraph">Situația poate părea artificială, deoarece știm că funcția callSomeFunc nu este definită. Cu toate acestea, într-o programare extinsă, unde diferiți dezvoltatori au definit diferite părți ale programului, devine mai dificil să controlezi codul. Există multe situații în care unele erori pot fi anticipate și prevenite, iar altele nu.</p>
     <p class="paragraph">Pentru gestionarea acestor situații, JavaScript furnizează construcția try...catch...finally, care are următoarea definiție formală:</p>
     <div class="code-inline">
      <pre><code>try&nbsp;{<br>&nbsp;//&nbsp;instrucțiuni&nbsp;blocului&nbsp;try<br>}<br>catch&nbsp;(error)&nbsp;{<br>&nbsp;//&nbsp;instrucțiuni&nbsp;blocului&nbsp;catch<br>}<br>finally&nbsp;{<br>&nbsp;//&nbsp;instrucțiuni&nbsp;blocului&nbsp;finally<br>}</code></pre>
     </div>
     <p class="paragraph">După operatorul try, se definește un bloc de cod. În acest bloc sunt plasate instrucțiunile pentru care poate apărea o eroare potențială în timpul execuției.</p>
     <p class="paragraph">Următorul este operatorul catch. După acest operator, în paranteze rotunde, se specifică numele obiectului care va conține informații despre eroare. Apoi urmează blocul catch. Acest bloc este executat doar în cazul apariției unei erori în blocul try.</p>
     <p class="paragraph">După blocul catch, urmează operatorul finally, cu propriul său bloc de instrucțiuni. Acest bloc este executat la sfârșitul blocurilor try și catch, indiferent dacă a apărut o eroare sau nu.</p>
     <p class="paragraph">Este de remarcat faptul că doar blocul try este obligatoriu. Unul dintre celelalte blocuri - catch sau finally - poate fi omis. Cu toate acestea, unul dintre aceste blocuri (fie catch, fie finally) trebuie să fie prezent. Cu alte cuvinte, putem utiliza următoarele variante ale acestei construcții:</p>
     <p class="paragraph">try...catch try...finally try...catch...finally</p>
     <p class="paragraph">De exemplu, să gestionăm situația anterioară cu funcția care nu există folosind această construcție:</p>
     <div class="code-inline">
      <pre><code>try&nbsp;{<br>&nbsp;&nbsp;&nbsp;callSomeFunc();<br>&nbsp;&nbsp;&nbsp;console.log("Sfârșitul&nbsp;blocului&nbsp;try");<br>}<br>catch&nbsp;{<br>&nbsp;&nbsp;&nbsp;console.log("A&nbsp;apărut&nbsp;o&nbsp;eroare!");<br>}<br>console.log("Celelalte&nbsp;instrucțiuni");</code></pre>
     </div>
     <p class="paragraph">Astfel, mai întâi se execută blocul try. Cu toate acestea, în timpul executării primei instrucțiuni - apelul funcției callSomeFunc() - apare o eroare. Acest lucru duce la faptul că toate instrucțiunile ulterioare din blocul try NU vor fi executate.</p>
     <p class="paragraph">Controlul se mută la blocul catch. În acest bloc se afișează un mesaj că a apărut o eroare. După executarea blocului catch, sunt efectuate celelalte instrucțiuni ale programului. Astfel, programul nu își întrerupe execuția în caz de eroare și își continuă activitatea.</p>
     <p class="paragraph">A apărut o eroare! Alte instrucțiuni</p>
     <p class="paragraph">Să luăm în considerare un alt exemplu:</p>
     <div class="code-inline">
      <pre><code>function&nbsp;callSomeFunc()&nbsp;{&nbsp;console.log("Funcția&nbsp;callSomeFunc");&nbsp;}<br><br>try&nbsp;{<br>&nbsp;&nbsp;&nbsp;callSomeFunc();<br>&nbsp;&nbsp;&nbsp;console.log("Sfârșitul&nbsp;blocului&nbsp;try");<br>}&nbsp;catch&nbsp;(error)&nbsp;{<br>&nbsp;&nbsp;&nbsp;console.log("A&nbsp;apărut&nbsp;o&nbsp;eroare!");<br>}<br><br>console.log("Alte&nbsp;instrucțiuni");</code></pre>
     </div>
     <p class="paragraph">Acum funcția callSomeFunc() este definită în program, astfel încât la apelarea funcției nu va apărea nicio eroare, iar blocul try va continua să se execute până la sfârșit. În absența unei erori, blocul catch nu va fi executat. Output-ul în consolă va fi următorul:</p>
     <p class="paragraph">Funcția callSomeFunc Sfârșitul blocului try Alte instrucțiuni</p>
     <h2 class="subtitle">Obținerea unei erori în blocul catch</h2>
     <p class="paragraph">În calitate de parametru pentru blocul catch, este furnizat un obiect cu informații despre eroare.</p>
     <div class="code-inline">
      <pre><code>try&nbsp;{<br>&nbsp;&nbsp;&nbsp;callSomeFunc();<br>&nbsp;&nbsp;&nbsp;console.log("Sfârșitul&nbsp;blocului&nbsp;try");<br>}&nbsp;catch&nbsp;(eroare)&nbsp;{<br>&nbsp;&nbsp;&nbsp;console.log("A&nbsp;apărut&nbsp;o&nbsp;eroare!");<br>&nbsp;&nbsp;&nbsp;console.log(eroare);<br>}</code></pre>
     </div>
     <p class="paragraph">În acest caz, vom obține un output în consolă similar cu următorul:</p>
     <div class="code-inline">
      <pre><code>A&nbsp;apărut&nbsp;o&nbsp;eroare!<br>ReferenceError:&nbsp;callSomeFunc&nbsp;is&nbsp;not&nbsp;defined<br>&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;index.html:35</code></pre>
     </div>
     <h2 class="subtitle">Bloc finally</h2>
     <p class="paragraph">Construcția try poate include și un bloc finally. Acest bloc poate fi utilizat împreună cu blocul catch sau în locul acestuia. Blocul finally se execută indiferent dacă apare o eroare sau nu. De exemplu:</p>
     <div class="code-inline">
      <pre><code>try&nbsp;{<br>&nbsp;&nbsp;&nbsp;callSomeFunc();<br>&nbsp;&nbsp;&nbsp;console.log("Sfârșitul&nbsp;blocului&nbsp;try");<br>}&nbsp;catch&nbsp;{<br>&nbsp;&nbsp;&nbsp;console.log("A&nbsp;apărut&nbsp;o&nbsp;eroare");<br>}&nbsp;finally&nbsp;{<br>&nbsp;&nbsp;&nbsp;console.log("Bloc&nbsp;finally");<br>}<br><br>console.log("Alte&nbsp;instrucțiuni");</code></pre>
     </div>
     <p class="paragraph">Output-ul în consolă al programului ar fi:</p>
     <div class="code-inline">
      <pre><code>A&nbsp;apărut&nbsp;o&nbsp;eroare<br>Bloc&nbsp;finally<br>Alte&nbsp;instrucțiuni</code></pre>
     </div>
     <p class="paragraph">Dacă eliminăm blocul catch și lăsăm doar blocul finally, eroarea nu va fi gestionată, iar programul se va încheia cu o eroare. Cu toate acestea, blocul finally va fi totuși executat:</p>
     <div class="code-inline">
      <pre><code>try&nbsp;{<br>&nbsp;&nbsp;&nbsp;callSomeFunc();<br>&nbsp;&nbsp;&nbsp;console.log("Sfârșitul&nbsp;blocului&nbsp;try");<br>}&nbsp;finally&nbsp;{<br>&nbsp;&nbsp;&nbsp;console.log("Bloc&nbsp;finally");<br>}<br><br>console.log("Alte&nbsp;instrucțiuni");</code></pre>
     </div>
     <p class="paragraph">Output-ul în consolă al programului ar fi:</p>
     <div class="code-inline">
      <pre><code>Bloc&nbsp;finally<br>Uncaught&nbsp;ReferenceError:&nbsp;callSomeFunc&nbsp;is&nbsp;not&nbsp;defined</code></pre>
     </div>
    </div>
   </main>
   <aside class="ad-section">
    <div class="ad-box">
     <p>Google Ad Here</p>
    </div>
    <div class="ad-box">
     <p>Promo: SQL Beginner Guide</p>
    </div>
   </aside>
  </div>
  <div class="lesson-navigation">
   <th:block th:if="${previousLesson != null}">
    <a th:href="@{'/lectii/' +
            ${#strings.toLowerCase(#strings.replace(previousLesson.chapter.topic.name, ' ', '-'))} + '/' +
            ${#strings.toLowerCase(#strings.replace(previousLesson.chapter.title, ' ', '-'))} + '/' +
            ${#strings.toLowerCase(#strings.replace(previousLesson.title, ' ', '-'))} }" class="nav-button">← Lecția anterioară</a>
   </th:block> <th:block th:if="${nextLesson != null}">
    <a th:href="@{'/lectii/' +
            ${#strings.toLowerCase(#strings.replace(nextLesson.chapter.topic.name, ' ', '-'))} + '/' +
            ${#strings.toLowerCase(#strings.replace(nextLesson.chapter.title, ' ', '-'))} + '/' +
            ${#strings.toLowerCase(#strings.replace(nextLesson.title, ' ', '-'))} }" class="nav-button">Lecția următoare →</a>
   </th:block>
  </div>
  <div th:replace="~{fragments/footer :: footer}"></div>
  <script th:src="@{/js/script.js}" defer></script>
 </body>
</html>
